spring:
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/database_distribution?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ENC#ZIZ0vdjV6HBQEGKi3FNIy9gYfs4GvaGBxHYj8MZfkC0ZtSFdGOUmgBOAT8y6uHYD
    password: ENC#ktHZOyAxa09PASaXGnaWhEbn9VPaz8hs2T8TAHTZrHKn6HE1nxaxzlLhREqS3bvm
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
  application:
    name: database-distribution
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  base-packages: com.tuituidan.openhub.mapper
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tuituidan.openhub.bean.entity
server:
  port: 8084

app:
  jdbc-url-template: jdbc:mysql://{}:{}/{}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  sql-database: select SCHEMA_NAME from information_schema.SCHEMATA where SCHEMA_NAME not in ('mysql', 'information_schema', 'performance_schema', 'sys')
  sql-database-table: select TABLE_NAME from information_schema.TABLES where TABLE_SCHEMA ='{}'
  sql-database-table-column: select COLUMN_NAME from information_schema.`COLUMNS` where TABLE_SCHEMA = '{}' and TABLE_NAME ='{}' order by ORDINAL_POSITION
  sql-table-struct: select table_schema,table_name,column_name,ordinal_position from information_schema.columns where table_schema = '{}' and table_name = '{}'
  sql-increment-search: select * from {}.{} where {} > '{}'
  sql-primary-key-search: select * from {}.{} where {} in ('{}')

dictionary:
  # 数据字典类型，xlsx-从excel中获取，database-从数据库中获取，需要配置查询sql，remote-远程获取，需要配置url
  type: xlsx
thread-pool:
  queue-size: 2000
  thread-name-prefix: database-distribution
